version: '3.8'

services:
  mongo:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    container_name: "scrabble_mongo"
    logging:
      options:
        max-size: 1g
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "scrabble"
#      MONGO_INITDB_ROOT_PASSWORD: "scrabble"
    ports:
      - '27017:27017'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    restart: always


  mq:
    image: rabbitmq:3-management-alpine
    container_name: scrabble_mq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ~/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/rabbitmq/log/:/var/log/rabbitmq
    restart: always

  cdc:
    build:
      context: .
      dockerfile: .docker/Dockerfile.cdc
    container_name: scrabble_cdc
    depends_on:
      - mongo
      - mq
    restart: always
    environment:
      - MONGO_DATABASE_HOST=mongodb://mongo:27017/?replicaSet=rs0
      - MONGO_DATABASE_NAME=scrabble


volumes:
  mongo_data:
  mongo_config:
  qdrant_data:


