[tool.poetry]
name = "cdc"
version = "0.1.0"
description = ""
authors = ["Vesa Alexandru"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pymongo = "^4.6.3"
pydantic-settings = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
